// apps/from-reducer-react-global-example/src/app/users/users.component.tsx
import {
  useDispatch,
  useSelector,
} from '@benji-toolkit/from-reducer-react-bindings';
import { getRepositories } from '@benji-toolkit/repositories';
import { getUsers } from '@benji-toolkit/users';
import React, { useEffect } from 'react';

export const Users = () => {
  const dispatch = useDispatch();
  const state = useSelector((x) => x);

  useEffect(() => {
    dispatch(getUsers());
    dispatch(getRepositories());
  }, [dispatch]);

  return (
    !!state && (
      <div>
        <pre>
          <code>{JSON.stringify(state, null, 2)}</code>
        </pre>
      </div>
    )
  );
};

// apps/from-reducer-angular-global-example/src/app/users/users.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { getRepositories } from '@benji-toolkit/repositories';
import { getUsers } from '@benji-toolkit/users';
import { dispatch, state$ } from '../store';

@Component({
  selector: 'app-users',
  template: `
    <div *ngIf="state$ | async as state">
      <pre>{{ state | json }}</pre>
    </div>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class UsersComponent {
  readonly state$ = state$;

  constructor() {
    dispatch(getUsers());
    dispatch(getRepositories());
  }
}
