// apps/from-reducer-react-local-example/src/app/users/users.component.tsx
import { fromReducer } from '@benji-toolkit/from-reducer';
import {
  getUsers,
  userEpics,
  usersInitialState,
  usersReducer,
  UsersState,
} from '@benji-toolkit/users';
import React, { useEffect, useState } from 'react';
import { Subscription } from 'rxjs';

const [state$, dispatch, combineEpics] = fromReducer(
  usersReducer,
  usersInitialState
);

export const Users = () => {
  const [state, setState] = useState<UsersState | null>(null);

  useEffect(() => {
    const subscription = new Subscription();
    const effects$ = combineEpics(...userEpics);

    subscription.add(state$.subscribe(setState));
    subscription.add(effects$.subscribe());

    dispatch(getUsers());

    return () => subscription.unsubscribe();
  }, [state$, dispatch]);

  return (
    !!state && (
      <div>
        <pre>
          <code>{JSON.stringify(state, null, 2)}</code>
        </pre>
      </div>
    )
  );
};

// apps/from-reducer-angular-local-example/src/app/users/users.component.ts
import {
  AfterViewInit,
  ChangeDetectionStrategy,
  Component,
  OnDestroy,
} from '@angular/core';
import { fromReducer } from '@benji-toolkit/from-reducer';
import {
  getUsers,
  userEpics,
  usersInitialState,
  usersReducer,
} from '@benji-toolkit/users';
import { Subscription } from 'rxjs';

const [state$, dispatch, combineEpics] = fromReducer(
  usersReducer,
  usersInitialState
);

@Component({
  selector: 'app-users',
  template: `
    <div *ngIf="state$ | async as state">
      <pre>{{ state | json }}</pre>
    </div>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class UsersComponent implements AfterViewInit, OnDestroy {
  readonly state$ = state$;

  private readonly subscription = new Subscription();

  ngAfterViewInit(): void {
    const effects$ = combineEpics(...userEpics);
    this.subscription.add(effects$.subscribe());
    dispatch(getUsers());
  }

  ngOnDestroy(): void {
    this.subscription.unsubscribe();
  }
}
